[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
web-sys = "0.3.56"
reqwest = "0.11.9"
wasm-bindgen-futures = "0.4.29"
serde_json = "1"